name: formz_input
description:  allow us to work with a validated object rather than a primitive types.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  formz: ^0.4.0

dev_dependencies:
  very_good_analysis: ^3.1.0