name: storage_repository
description: A dart client for storing data.
version: 1.0.0
publish_to: none

environment: 
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.3.8

dependencies:
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  test: ^1.17.10
